FROM node:18

WORKDIR /usr/src/app

COPY package.json ./
COPY prisma/ ./prisma/
RUN rm -Rf prisma/migrations
COPY tsconfig.json ./tsconfig.json

RUN npm i -g pnpm
RUN pnpm add @prisma/client
RUN npx prisma generate
RUN pnpm install
RUN pnpm add -D tsconfig-paths ts-node typescript

COPY ./prisma/seed.ts ./prisma/

# Usar un comando modificado que configura correctamente ts-node
CMD ["npx", "ts-node", "--transpile-only", "--compiler-options", "{\"module\":\"CommonJS\"}", "prisma/seed.ts"]